remote_theme: tuur29/pages-themes-cayman
title: Show My Music
description: "show the current playing track on your stream"
markdown: kramdown
url: https://code.sitton.dev
baseurl: /show-my-music

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  
color:
  gradient_left: "#eacda3"
  gradient_right: "#d6ae7b"
  
darkmode: true
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css

show_downloads: true
buttons:
  zip_hide: true
  tar_title: About me
  tar_url: /
  tar_hide: false
